### ISSUE TITLE
Does not work with check_mk 1.2.8

### ISSUE THREAD

**Issue by stemod** [disconn3ct/cmk-rabbitmq#3]
The only error shown:

```
Check parameter definition for rabbitmq_queues has type Dictionary, but match_type first
```

**Comment by disconn3ct** [comment]
Can you be more specific?

**Comment by awiamo** [comment]
In file ../plugins/wato/rabbitmq_queues_check_parameters.py change the: "first",  to "dict",

**Comment by fn-dis** [comment]
Thanks, sorry about missing your second update. I'd have gotten it a lot faster.
